[[constraint]]
  name = "github.com/openfaas/faas"
  version = "0.6.16"

[[constraint]]
  name = "github.com/gogo/protobuf"
  revision = "dda3e8acadcc9affc16faf33fbb229db78399245"

[[constraint]]
  name = "github.com/nats-io/go-nats"
  revision = "34c8842105ac0b69c838a9998a239d482936c466"

[[constraint]]
  name = "github.com/nats-io/go-nats-streaming"
  revision = "bf8654e90f5296da96eab1e85808eb5c4b7b5541"

[[constraint]]
  name = "github.com/nats-io/nuid"
  revision = "3cf34f9fca4e88afa9da8eabd75e3326c9941b44"
  