name: publish

on:
  push:
    tags:
      - '*'
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@master
      - name: Install Go
        uses: actions/setup-go@master
        with:
          go-version: 1.23.x
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Get TAG
        id: get_tag
        run: echo TAG=${GITHUB_REF#refs/tags/} >> $GITHUB_ENV

      - name: Get git commit
        id: get_git_commit
        run: echo "GIT_COMMIT=$(git rev-parse HEAD)" >> $GITHUB_ENV
      - name: Get version
        id: get_version
        run: echo "VERSION=$(git describe --tags --dirty)" >> $GITHUB_ENV
      - name: Get Repo Owner
        id: get_repo_owner
        run: echo "REPO_OWNER=$(echo ${{ github.repository_owner }} | tr '[:upper:]' '[:lower:]')" > $GITHUB_ENV


      - name: Login to Docker Registry
        uses: docker/login-action@v3
        with:
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
          registry: ghcr.io
      - name: Publish multi-arch containers to GHCR
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          outputs: "type=registry,push=true"
          platforms: linux/amd64,linux/arm64
          build-args: |
            VERSION=${{ env.TAG }}
            GIT_COMMIT=${{ github.sha }}
          tags: |
            ghcr.io/${{ env.REPO_OWNER }}/queue-worker:${{ env.TAG }}
            ghcr.io/${{ env.REPO_OWNER }}/queue-worker:${{ github.sha }}
            ghcr.io/${{ env.REPO_OWNER }}/queue-worker:latest
